// MANAGED FILE — generated by opencode-host/generate.py; do not edit by hand (re-vendor instead).
// The runtime below is pinned by RUNTIME.sha256; this file only wires it up.
import { defineHostPlugin } from "./runtime.ts"

export default defineHostPlugin({
  "agentNamespace": "grok-bitch",
  "agentsDirs": [
    "agents"
  ],
  "applyAgentTiers": true,
  "cage": {
    "defaultProtected": [],
    "verifies": {
      "adapter-validate": "python3 {root}/scripts/opencode-validate.py"
    }
  },
  "canonicalRuntimeSha": "cb716a4c3e23e33a103717da1cc008618a7972acd3ea85df5105a690fc7d4919",
  "commandAliases": [
    "adventure-mode",
    "auto-rick",
    "blips-n-chitz",
    "council",
    "cronenberg",
    "detox",
    "episode",
    "explicit",
    "family-mode",
    "jerry-swarm",
    "jerry-test",
    "pickle-rick",
    "rick-git",
    "rick-mode"
  ],
  "commandHostNote": "---\n**OpenCode host note (managed).** In this host you orchestrate by composing the plugin's\n**safe workflow primitives** from OpenCode Code Mode \u2014 ordinary JavaScript calling\npermission-checked tools. No workflow script is ever evaluated by the plugin process.\n\n1. `const {runId} = await tools[\"grok-bitch\"].workflow_start({name})`\n2. Each step: `await tools[\"grok-bitch\"].workflow_agent({runId, prompt, agentType:\"grok-bitch:<cast>\",\n   label, phase, schema, timeoutMs, worktree})` \u2192 returns\n   `{ok, status, report, claim, guard, verify, output, childSessionID, sessionOutcome}`.\n3. Compose with ordinary JS: `Promise.all([...])` for parallel bearings, loops for\n   pipelines, conditionals for branching \u2014 all inside Code Mode's sandbox.\n4. Record/inspect: `workflow_phase`, `workflow_log`, `workflow_status({runId})`,\n   `workflow_cancel({runId})`, `workflow_finish`.\n\nA child's `report`/`claim` is **testimony**. `status`, `guard`, and `verify` are\nmechanical and are what the caller may rely on; the caller (Rick) independently\nre-checks. There is no hosted `/workflows` pane.",
  "commandsDirs": [
    "commands"
  ],
  "hooks": [
    {
      "claudeEvent": "SubagentStop",
      "command": "python3 {root}/scripts/label_lint.py --hook",
      "ownsOutcomeContract": true,
      "timeoutMs": 10000
    }
  ],
  "hostTested": "2.0.14",
  "id": "grok-bitch",
  "name": "grok-bitch",
  "registerCommands": true,
  "registerMcp": true,
  "registerSkills": true,
  "runtimeApi": "opencode-2.0.14",
  "runtimeVersion": "2.0.0",
  "skillsDirs": [
    "skills"
  ],
  "tierRoles": {
    "haiku": "cheap",
    "opus": "reasoning-heavy",
    "sonnet": "directed"
  },
  "tiers": {},
  "version": "2.2.2",
  "workflow": true
})
